### ISSUE TITLE
A parameter is incorrectly ignored

### ISSUE THREAD

**Issue by RussBaz** [nicklockwood/SwiftFormat#1688] opened 2024-04-26 06:44 UTC
The following snippet causes `SwiftFormat` to break the code:

```swift
func urlTestContains(path: String, strict _: Bool = true) -> Bool {
    let path = if path.hasSuffix("/") { path } else { "\(path)/" }

    return false
}
```

It does not detect that the `path` variable is used, and it will insert`_` to the function signature.

I am sorry I could not describe the issue any better and could not verify if it was previously reported. Please have a look.

I am using `swiftformat` version 0.53.8.

Thank you.

**Comment by calda** [comment] 2024-04-28 14:52
Should be fixed by https://github.com/nicklockwood/SwiftFormat/pull/1687

**Comment by nicklockwood** [comment] 2024-05-12 20:29
@RussBaz fix landed in 0.53.9

**Closed by nicklockwood** 2024-05-12 20:29 UTC
Labels: bug, fixed in develop

**Comment by RussBaz** [comment] 2024-08-10 16:30
Hi again. It seems like this issue has resurfaced for me. I am using `0.54.3`. Can you check this?

**Comment by calda** [comment] 2024-08-10 16:44
I can't reproduce this issue with the `func urlTestContains` sample code above, can you share new sample code that demonstrates the problem?

**Comment by RussBaz** [comment] 2024-08-10 16:51
This seems to reproduce my problem:

```swift
enum Sample {
    static func invite(lang: String, randomValue: Int) -> String {
        let flag: String? = if randomValue > 0 { "hello" } else { nil }

        let lang = if let flag { flag } else { lang }

        return lang
    }
}
```

**Comment by calda** [comment] 2024-08-10 17:29
Thanks for the sample code, here's a fix: https://github.com/nicklockwood/SwiftFormat/pull/1815
