### ISSUE TITLE
Error:    #if(iOS) formatted into #ifiOS

### ISSUE THREAD

**Issue by timbms** [nicklockwood/SwiftFormat#545] opened 2020-01-25 13:27 UTC
Hi, 
I am using swiftformat 0.44.0
It corrupts one file where I make use of `#if(iOS)`.
All instance are turned into         
`#ifiOS`
Can you please have a look

**Comment by nicklockwood** [comment] 2020-01-25 17:17
@timbms thanks for reporting. It looks like this is caused by the `redundantParens` rule, so disabling that rule should be a workaround for now.

**Comment by timbms** [comment] 2020-01-25 17:31
Confirmed: This workaround is effective. I was so far excluding the relevant file

**Comment by nicklockwood** [comment] 2020-01-25 17:59
@timbms if that's the only place it happens, you can also fix it by just manually inserting a space after the #if - SwiftFormat won't remove it again.

**Comment by nicklockwood** [comment] 2020-01-26 16:53
@timbms fixed in 0.44.1.

**Closed by nicklockwood** 2020-01-26 16:53 UTC
