### ISSUE TITLE
anyObjectProtocol  is not working, version 0.40.0

### ISSUE THREAD

**Issue by CodeEagle** [nicklockwood/SwiftFormat#382] opened 2019-03-18 03:44 UTC
`testclass.swift`
```swift
import Foundation 
protocol Test: class { }
```

try 0x01: using config file with `--swiftversion 4.2`, not formatted as expected.
try 0x02: using command-line `swiftformat --swiftversion 4.2 testclass.swift `, not formatted as expected.
try 0x03: using `.swift-version` with `4.2` in it, not formatted as expected.

**Comment by CodeEagle** [comment] 2019-03-18 08:38
also `redundantLet`

swiftformat version: 0.40.0

**Comment by nicklockwood** [comment] 2019-03-18 08:52
@codeeagle can you provide a code sample for `redundantLet` failing? It's not tied to a specific swift version, so I think it's probably an unrelated bug.

**Comment by CodeEagle** [comment] 2019-03-18 08:56
`redundantLet` not related to specific swift version, just found it not work while testing anyObjectProtocol

**Comment by nicklockwood** [comment] 2019-03-18 09:11
@CodeEagle I'd still like a code sample please, so I can reproduce it.

**Comment by CodeEagle** [comment] 2019-03-18 09:21
@nicklockwood sorry, I misunderstand `redundantLet `,
 I though it will turn 
unused `a` from `let a = "asc"` to `_ = "asc"`

**Comment by nicklockwood** [comment] 2019-03-18 09:27
@CodeEagle oh, I see. Well, maybe it should, but it doesn't currently :-)

**Comment by nicklockwood** [comment] 2019-03-18 09:33
@CodeEagle I've opened a feature request for a rule to do what you expected redundantLet to do: https://github.com/nicklockwood/SwiftFormat/issues/387

**Comment by CodeEagle** [comment] 2019-03-18 09:35
@nicklockwood nice

**Comment by nicklockwood** [comment] 2019-03-19 01:58
@CodeEagle it turns out that there was a bug with the `--swiftversion` flag. Fixed in 0.40.2.

**Closed by nicklockwood** 2019-03-19 01:58 UTC
Labels: fixed in develop
