### ISSUE TITLE
--unusedArguments breaks code when function argument has the same name as a computed property in the same class

### ISSUE THREAD

**Issue by keithburgoyne** [nicklockwood/SwiftFormat#1489] opened 2023-07-28 15:30 UTC
A class with the following:

```
final class someClass {

var someValue: Type? {
   ...
}

func someFunction(someValue: Type) {
    someValue.someCalculation()
   ...
}
```

... will have the function rewritten to the following:
```
func someFunction(someValue _: Type) {
    someValue.someCalculation() // This is an error, since someValue is scoped to be the computed property above, which is optional.
   ...
}
```

Ideally, `SwiftFormat` would check to ensure there isn't a variable in the local scope before assuming the value belongs to the class.

**Comment by nicklockwood** [comment] 2023-07-28 21:44
@keithburgoyne I wasn't able to reproduce this bug with the sample you provided - perhaps it's been simplified down too much from the original case?

Also, just to confirm - which version of SwiftFormat are you using, and how are you running it? (command line, Xcode extension, etc?)

**Comment by jshier** [comment] 2023-08-01 21:29
I have a similar bug (if not similar enough I can open a new issue) where closure parameters are improperly removed. I don't have any ivar usage of the name, and other uses of the same API don't have the parameter removed, so it's unclear what's unique about this example.

```swift
public func resolvePayment(for intent: RepeatOrderIntent, with completion: @escaping (RepeatOrderPaymentResolutionResult) -> Void) {
        resolveOrderState(for: intent) { _, _, availablePaymentTypes in // availablePaymentTypes always removed
            guard
                let inPaymentMethod = intent.payment,
                availablePaymentTypes.contains(where: { $0.inPaymentMethod == inPaymentMethod })
            else {
                completion(.needsValue())
                return
            }

            completion(.success(with: inPaymentMethod))
        } failure: { _ in
            completion(.needsValue())
        }
    }
```

**Comment by nicklockwood** [comment] 2023-08-01 21:49
@jshier it's probably not the same issue, but don't worry about opening a new issue for now. The rule doesn't check for the existence of ivars (there's enough context within the method body itself) so it's unlikely that's a factor.

**Comment by nicklockwood** [comment] 2023-08-05 14:37
@jshier your bug is fixed by https://github.com/nicklockwood/SwiftFormat/issues/1495. I'm not sure whether the same fix solves your issue @keithburgoyne, but I'm going to assume it does until you tell me otherwise.

**Closed by nicklockwood** 2023-08-05 14:37 UTC
Labels: can't reproduce

**Comment by jshier** [comment] 2023-08-06 17:36
@nicklockwood 0.51.14 doesn't seem to fix my particular example. `availablePaymentTypes` is still removed.

**Comment by nicklockwood** [comment] 2023-08-06 18:22
@jshier oh, sorry about that. It's very strange because I added almost that exact example as a test case. I'll try again.

**Comment by nicklockwood** [comment] 2023-08-06 18:33
@jshier huh, from the commit log it looks like I somehow reverted all the fixes in the update commit 🤦‍♂️

**Comment by nicklockwood** [comment] 2023-08-06 19:19
@jshier OK, the fix is included in 0.51.15 (for real this time!)

**Comment by jshier** [comment] 2023-08-06 19:23
Confirmed, thanks!
