### ISSUE TITLE
Using globs in config file significantly slows down SwiftFormat

### ISSUE THREAD

**Issue by mgrebenets** [nicklockwood/SwiftFormat#329] opened 2018-12-10 02:20 UTC
It's the first time I'm trying to use the globs added in https://github.com/nicklockwood/SwiftFormat/issues/301.

After I add a simple `*SwiftGen*` glob, I notice that it significantly slows down `swiftformat` run time.

For the same number of files (116 in this example),
- Running `swiftformat` with globs in config: **11.69s**
- Running `swiftformat` without any globs in config: **0.69s**

There's almost 20 times increase in execution time.

Not sure if processing globs should really slow down the execution.
On the opposite, since with globs more files are ignored, it should run even faster.

Using `swiftformat` in git commit hooks or in Xcode build phase will add this extra delay.
I've noticed that the more globs there are in config, the longer it takes.

Looks like options parsing code in `CommandLine.swift` is slow when it comes to using `expandGlobs`. I've never used this API, so I'm not quite sure why is it slow and if it can be improved to be faster.

**Comment by mgrebenets** [comment] 2018-12-10 02:20
Also, while globs are implemented, it's not clear what's the exact syntax for them.
Could the README be updated with a couple of examples please?
None of the globs I tried worked for me so far.

**Comment by nicklockwood** [comment] 2018-12-10 09:00
Thanks for reporting.

I’d expect there to be a slight overhead due to running a regex match on the file paths, but nothing like as bad as that.

I’ll look into it.

**Comment by mgrebenets** [comment] 2018-12-11 02:50
Maybe something like this would work: https://github.com/realm/SwiftLint/pull/2316/files
Though I think SwiftLint's globbing may be improved a bit, but it could be a good starting point.

**Comment by nicklockwood** [comment] 2018-12-13 14:06
@mgrebenets I wasn't able to reproduce the performance problem you were seeing with using globs. Are you able to share your project so I can try to reproduce the issue?

**Comment by mgrebenets** [comment] 2018-12-14 00:13
@nicklockwood 
I may be able to create a dummy project with similar number of files and directories and similar nesting levels.

**Comment by nicklockwood** [comment] 2018-12-14 10:16
@mgrebenets that would be very helpful 👍

**Comment by nicklockwood** [comment] 2018-12-15 00:15
@mgrebenets I've made some improvements to glob performance in version 0.36.0. See if that solves your issue.

**Comment by mgrebenets** [comment] 2018-12-17 01:20
While I couldn't measure exactly how 0.36.0 did compared to 0.35.10, but I did figure out a few "rules of thumb" to help me with my issue.

I had to make sure to follow these simple rules:
- Use non-glob patterns first
- Put exclude rules for largest folders first, e.g. put `.git` first

So pretty much excluding large folders at the very beginning, will then significantly reduce overall number of files and folders for which the glob patterns need to be expanded.

For the rather large project that we've got, the total time running SwiftFormat for all files is now around `25s`, which is not bad and it doesn't take that long to resolve matches. In day to day work we lint single files or smaller nested folders of the whole project.

Adding a single pattern like `**/*Keyword*` adds 1s on average to overall execution time.

**Comment by nicklockwood** [comment] 2018-12-17 09:10
@mgrebenets it definitely seems like your project is quite unlike any I’ve tested on. The most complex project I’ve tried takes <1s, even with a wildcard **/Pods rule.

It would be really helpful if you could share the folder structure at least. It would be fine to remove all of the actual swift files (or replace them with empty files if that doesn’t recreate the issue).

Some extra tips that might help in the meantime:

Hidden files and folders such as .git are already ignored, so you can remove those from your globs (unless that somehow makes it worse in your case?)

Globs containing a / are more expensive (they have to scan the whole directory tree), so using separate .swiftformat files with their own file-level —exclude rules inside each subdirectory will probably be cheaper (though maybe too much effort to maintain)

**Comment by mgrebenets** [comment] 2018-12-17 11:49
@nicklockwood Thanks, will try the suggestion for hidden files (I had the following listed `.git`, `**/.vendor`, `.bundle`, `**/.fastlane`, etc. Will try removing them tomorrow.

I was able to create a demo project by mapping each file in our project into an empty file with MD5 hash for name. This gave me something I could share safely.

One thing I realized though, is that I also hashed names of folders like `.git`, `Pods`, `Carthage` and alike. Also I've removed all strings like `AutoGenerated` or `+SwiftGen` from file names.
This makes it too difficult to test globs.

I'll modify the hashing script to preserve those key folder names and file name parts and I think I'll be able to share the project then.

**Comment by mgrebenets** [comment] 2018-12-24 03:01
@nicklockwood 
Here it is: https://github.com/mgrebenets/swiftformat-globs-demo
It's a completely hashed meaningless bunch of files.
It does, potentially, reflect layout of some real monorepo, which re so popular these days ;)

Maybe it's a bit too large, but could be used for benchmarking and finding potential improvements in glob implementation I believe.

**Comment by mgrebenets** [comment] 2018-12-29 14:08
Yet another update.
What I've discovered today, is that a single glob can hugely impact overall performance.
If I use a single glob like `Doc[s]` I will get around `12s` execution time on the repo similar to the one I shared. I can see how it takes some time to resolve globs  before `running swiftformat...` message appears.

If, however, I replace the glob with `Doc,Docs`, the `running swiftformat...` message appears immediately and it takes only `1.5s` to format same code.

Maybe I'm wrong, but I think the root cause is glob expansion implementation.
As soon as a single glob is found, it then is expanded against the whole code base and a list of matching files is then built. If a repo is huge, one single glob will take a while. If there are more globs, it may be even longer.

The default non-glob approach seems to be like so:
- Iterate over all Swift files
- If file matches one of the paths on the exclude list - skip it

Probably instead of expanding globs and building up lists of matching files to exclude, instead the same straightforward approach could be used with slight modification:
- Iterate over all Swift files
- If file matches one of the paths on the exclude list **or if it matches one of the globs on the exclude list**, then skip it

And "match a glob" would be trying to use a glob as a regex, which is faster than expanding a glob.
I'm not yet sure how to convert a glob like `**/*Generated*` into a regex accounting for the fact that `**` means "recursive", but should be possible I guess, e.g. `(.*/)*.*Generated.*`.

**Comment by nicklockwood** [comment] 2018-12-29 14:39
@mgrebenets it works pretty much as you described. What’s not clear to me is why scanning the directory to expand the globs takes so much longer than scanning to format files.

I could probably improve performance by refactoring to do the glob matching and formatting in a single pass as you suggest, but even so I would expect that the current setup would only double the time taken at worst. The fact that it’s increasing it by orders of magnitude suggests there’s some sort of bug, and I’d like to identify what that is before refactoring anything.

**Comment by nicklockwood** [comment] 2018-12-30 19:20
@mgrebenets I found that a big chunk of time was being spent on regex matching. This was mainly because I was using Strings for regexes instead of precompiled NSRegularExpressions.

I've pushed a fix to the develop branch that uses NSRegularExpression instead, and that reduces the expandGlobs time considerably.

It's still taking a lot longer to run your example than I'd like, but that fix alone roughly halves the time. I'll keep investigating.

**Comment by nicklockwood** [comment] 2018-12-30 22:53
@mgrebenets I've now refactored to use a single pass and it's *dramatically faster*. Please try the version on develop branch and verify. I'll push a release shortly.

**Comment by mgrebenets** [comment] 2018-12-31 02:00
Hi @nicklockwood 

Seems to be much faster now 🎉 

I've tested with same `Doc,Docs` vs `Doc[s]` change.
Even though there are no Swift files in `Doc` or `Docs`, just adding glob used to cause slowdown.

Doesn't happen with version from `develop` branch. Glob version of config runs for the same time as non-glob version.

One thing I'm struggling with though, is making use of globs in configs.
I have a bunch of files sitting in the `Generated` folder and I want to ignore all of them, for example

`MyApp/Generated/AutoGenerated.swift`

No matter what kind of glob I try, nothing seems to be working:

- `**/Generated`
- `**/*Generated*`
- `*Generated*`
- `**/Generated/*`
- `.*Generated.*`
- `**/*.Generated`
- etc...

Whichever I try, `swiftformat` keeps picking up and formatting the file.

Am I using glob syntax incorrectly here?

**Comment by nicklockwood** [comment] 2018-12-31 17:47
@mgrebenets `--exclude **/Generated` is working fine for me. Can you remind me of your project folder structure?

I suspect it's something to do with the relative positions of the .swiftformat file and/or the swiftformat binary, but I've not been able to reproduce the problem locally using a structure like:

    Root
        .swiftformat (contains --exclude **/Generated)
        MyApp
                Generated (ignored)
                        AutoGenerated.swift
        MyOtherApp
                Generated (ignored)
                        AutoGenerated.swift

**Comment by nicklockwood** [comment] 2018-12-31 17:52
@mgrebenets are you using an explicit `--config` argument instead of relying on the nested `.swiftformat` file? I think that may have something to do with it.

**Comment by nicklockwood** [comment] 2018-12-31 19:05
@mgrebenets OK, I found a bug when using the `--config` argument. If that *was* the issue, then it should now be fixed on the develop branch.

**Comment by mgrebenets** [comment] 2019-01-01 00:18
Yep, I was explicitly specifying `--config` option. I’ll test again with develop in a bit 👍

**Comment by nicklockwood** [comment] 2019-01-01 17:34
@mgrebenets I'm going to assume this is fixed in 0.37.2. If not, feel free to reopen.

**Closed by nicklockwood** 2019-01-01 17:34 UTC

**Comment by mgrebenets** [comment] 2019-01-01 23:16
@nicklockwood 
Just tested it with tip of `develop` and all looks good.
Using globs like `**/Generated` has no impact on running time, the "running swiftformat..." message appears instantaneously. 

I am now able to significantly simplify list of exclude files in the config 🎉

**Comment by nicklockwood** [comment] 2019-01-01 23:18
@mgrebenets great! thanks for your patience, and your help with tracking down the issue 👍
