### ISSUE TITLE
`swiftformat:sort` does not work on `extension`

### ISSUE THREAD

**Issue by domkm** [nicklockwood/SwiftFormat#1622] opened 2024-02-05 04:10 UTC
`// swiftformat:sort` before `extension` does not sort declarations inside the extension.

**Comment by calda** [comment] 2024-02-17 23:09
I think what must be going on is:
 1. You have both the `organizeDeclarations` and `sortDeclarations` rules enabled. When this is the case, `sortDeclarations` would never attempt to sort a declaration body, since that could conflict with `organizeDeclarations` (which implements its own sorting support)
 2. Your `organizeTypes` option excludes `extension` (the default value is `class,actor,struct,enum`). This made it so the `organizeTypes` rule didn't run on extensions. So there was no rule that would attempt to sort this declaration.

https://github.com/nicklockwood/SwiftFormat/pull/1628 fixes this so that the `sortDeclarations` will still sort the body of any declaration type excluded from `organizeDeclarations` via the `organizeTypes` option.

**Comment by domkm** [comment] 2024-02-29 23:38
Thanks for fixing this!

I did have both `organizeDeclarations` and `sortDeclarations` enabled. However, I was using `--organizetypes class,actor,struct,enum,extension,protocol` so I thought it would both organize and sort within extensions.

**Comment by calda** [comment] 2024-03-02 16:30
Is your issue fixed in [0.53.3](https://github.com/nicklockwood/SwiftFormat/releases/tag/0.53.3)? If not can you share more details to help me reproduce the issue (sharing a test case with a standalone swift file that reproduces the issue when running a specific SwiftFormat command)?

**Comment by nicklockwood** [comment] 2024-03-09 06:24
@domkm I'm assuming this is fixed. Feel free to reopen if not

**Closed by nicklockwood** 2024-03-09 06:24 UTC
