### ISSUE TITLE
Formatter introduces breaking trailing closure syntax for specific function signatures

### ISSUE THREAD

**Issue by sfktrifork** [nicklockwood/SwiftFormat#428] opened 2019-05-03 14:52 UTC
### Context

* A function's signature defines *n* parameters.
* All of the final *k* parameters are closures, where *k* >= 2.
* The *last* parameter (parameter no. *n*) has a default value.

### Problem

When the caller defers to the default value on parameter *n*, but specifies a value for parameter *n* - 1, SwiftFormat will erroneously assume parameter *n* - 1 to be the last parameter in the signature and format its value as a trailing closure.

Swift does *not* support trailing closure syntax in this circumstance.

## Example

Given the function:

```swift
func a(nMinusOne: (() -> Void)?, n: (() -> Void)? = nil) {}
```

A syntactically correct call to this function while deferring to the default value of parameter `n` looks like this:

```swift
a(nMinusOne: {})
```

However, SwiftFormat formats the function call like this, "breaking" the code:

```swift
a {}
```

## Observation

Observed while using UIKit, specifically `animate(alongsideTransition:completion:) -> Bool` on `UIViewControllerTransitionCoordinator`. The function's signature is provided here

```swift
func animate(alongsideTransition animation: ((UIViewControllerTransitionCoordinatorContext) -> Void)?, completion: ((UIViewControllerTransitionCoordinatorContext) -> Void)? = nil) -> Bool
```

 As per trailing closure syntax, the formatter is configured to format the function call

```swift
transitionCoordinator.animate(alongsideTransition: { _ in
  self.dimmingView.alpha = 1
})
```

as

```swift
transitionCoordinator.animate { _ in
  self.dimmingView.alpha = 1
}
```

...which does not compile.

**Comment by sfktrifork** [comment] 2019-05-03 14:55
I apologize for the overlong post. I couldn't find a way to state the problem more concisely.

**Comment by nicklockwood** [comment] 2019-05-27 12:02
Sorry for the delayed response. I believe I understand the issue. It's difficult to detect this problem at the call site, so the only option I can see at the moment is to add an explicit blacklist you can use for such functions. I'll consider it some more.

**Comment by nicklockwood** [comment] 2019-05-27 20:55
Note: in the most recent releases, SwiftFormat should only apply trailing closure syntax to *anonymous* closure arguments (which neither of your examples are). If you are finding that it's breaking cases with named closure arguments like your examples, please let me know.

**Comment by nicklockwood** [comment] 2019-06-12 09:18
Closing this since I can't reproduce on the latest SwiftFormat version. If you have more information please feel free to reopen.

**Closed by nicklockwood** 2019-06-12 09:18 UTC
