### ISSUE TITLE
class function replaced with enum.

### ISSUE THREAD

**Issue by destman** [nicklockwood/SwiftFormat#1195] opened 2022-06-15 10:30 UTC
What rule cause such replacement?  Or maybe this is a bug?
``` diff
- class override func show() {
+ enum override func show() {
```

**Comment by nicklockwood** [comment] 2022-06-15 15:59
That's the [enumNamespaces](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#enumNamespaces) rule

**Comment by destman** [comment] 2022-06-16 08:35
Hm. Looks like bug for me. No new types was created here. Just override of class function...

**Comment by nicklockwood** [comment] 2022-06-16 08:56
Oh sorry, I didn't look closely enough. Yes, this is clearly wrong 🤦‍♂️

**Comment by nicklockwood** [comment] 2022-06-18 16:28
@destman can you provide the whole source file, or a cutdown standalone sample the reproduces the issue when swiftformat is run on it? I can't reproduce it from that one line.

**Comment by destman** [comment] 2022-06-18 16:43
> @destman can you provide the whole source file, or a cutdown standalone sample the reproduces the issue when swiftformat is run on it? I can't reproduce it from that one line.

Shure. Here is minimal example that triggers this behaviour:
```swift
class Test {
    class override func show() {
        Boarding.instance?.present(instantinate())
    }
}

```
Version of swiftformat is 0.49.9.

**Comment by nicklockwood** [comment] 2022-06-18 21:49
@destman fixed in 0.49.10

**Closed by nicklockwood** 2022-06-18 21:49 UTC
Labels: bug, fixed in develop
