### ISSUE TITLE
0.49.15 is adding extra indents on any line with `async let`

### ISSUE THREAD

**Issue by simondelphia** [nicklockwood/SwiftFormat#1250] opened 2022-08-14 03:55 UTC
After upgrading to 0.49.15 all my lines with `async let` are getting extra indents

**Comment by nicklockwood** [comment] 2022-08-14 08:47
@simondelphia d'oh! thanks, I'll get this fixed.

**Comment by nicklockwood** [comment] 2022-08-14 08:57
@simondelphia can you provide a code example? I'm having trouble reproducing this.

**Comment by nicklockwood** [comment] 2022-08-14 09:40
I've identified the probable source of the bug and added a fix for it, but it would still be useful to have a test case since I wasn't able to reproduce the issue (cc @calda)

**Comment by simondelphia** [comment] 2022-08-14 14:29
I put this in a file in my test folder both with and without the swift format / swift version files as in #1224

```
func myFunc() {
    let x = 1
    enum Baz {
        case foo
    }
    async let foo = bar()
}
```

The async let line gets indented more than the other lines when using .15.

**Comment by nicklockwood** [comment] 2022-08-14 15:48
@simondelphia perfect, thanks!

It looks like the issue only happens after a closing brace, but the fix I already landed in develop solves it anyway.

**Comment by simondelphia** [comment] 2022-08-14 15:49
Heh, I added that enum rather randomly

**Comment by nicklockwood** [comment] 2022-08-14 15:54
OK, well if you find any other cases that aren't after a brace let me know and I'll add them to the test suite.

In the meantime, I'm not sure of any workarounds other than restructuring the code or adding

```swift
// swiftformat:disable:next indent
```

above the first `async let ...`

**Comment by simondelphia** [comment] 2022-08-14 17:40
Seems to be happening regardless of whether it appears after a closing brace for me

**Comment by choulepoka** [comment] 2022-08-15 02:17
If it helps the investigation.

Before formatting:

```
import Foundation

public struct LoadingStateService {

    private let api: Api

    public func willIndent(progress: Progress?) async throws -> Bool {
        progress?.totalUnitCount += 1
        async let serverConfig = try api.getConfig()
        return true
    }

    public func willNotIndent(progress: Progress?) async throws -> Bool {
        async let serverConfig = try api.getConfig()
        return true
    }

    public func willIndent2(progress: Progress?) async throws {
        progress?.totalUnitCount += 1
        async let serverConfig = try api.getConfig()
    }
}
```

After formatting:

```
import Foundation

public struct LoadingStateService {

    private let api: Api

    public func willIndent(progress: Progress?) async throws -> Bool {
        progress?.totalUnitCount += 1
            async let serverConfig = try api.getConfig()
        return true
    }

    public func willNotIndent(progress: Progress?) async throws -> Bool {
        async let serverConfig = try api.getConfig()
        return true
    }

    public func willIndent2(progress: Progress?) async throws {
        progress?.totalUnitCount += 1
            async let serverConfig = try api.getConfig()
    }

}

```

**Comment by nicklockwood** [comment] 2022-08-15 07:13
Got it. It seems to be only if the async let if preceded by other code that doesn't begin with `async`. In any case, all these cases are fixed now. I'll push a new release soon.

**Comment by nicklockwood** [comment] 2022-08-15 07:29
Fixed in 0.49.16

**Closed by nicklockwood** 2022-08-15 07:29 UTC
Labels: bug, fixed in develop

**Comment by simondelphia** [comment] 2022-08-15 12:25
How long does it usually take for the releases to show up on homebrew?

**Comment by nicklockwood** [comment] 2022-08-15 14:18
@simondelphia should be there now

**Comment by simondelphia** [comment] 2022-08-15 14:59
All green now, thank you!
