### ISSUE TITLE
--trimwhitespace "nonblank-lines" add spaces, while it shouldn't

### ISSUE THREAD

**Issue by castus** [nicklockwood/SwiftFormat#174] opened 2017-09-07 16:05 UTC
Let me explain what is the issue. I will mark spaces as dots.

Suppose I have 

```
class Foo {
[no-spaces-here-just-empty-line]
....print("abc")
}
```

When I run `swiftformat --trimwhitespace "nonblank-lines"`, it will add four spaces in the empty line, so it will be:

```
class Foo {
....
....print("abc")
}
```

Expected behaviour is that it will only trim spaces from lines, that aren't blank. It definitely shouldn't add new spaces to existing code ;)

What do you think?

**Comment by nicklockwood** [comment] 2017-09-07 16:12
This is expected behavior, although I can see why it would be confusing.

The default behavior is to remove all spaces from empty lines (which would leave your first example alone, and would convert the second example to the first).

If you override this by using `--trimwhitespace nonblank-lines` then it only trims the trailing space from lines that contain code, and leaves the other lines alone.

However, the `indent` rule indents every line according to its scope, including blank lines. So it is not that the `--trimwhitespace nonblank-lines` option is adding the space, it's that's it's failing to remove the space that has been added by the `indent` rule.

If you don't want this space to be added, I suggest leaving `--trimwhitespace` at the default setting.

**Comment by castus** [comment] 2017-09-07 20:10
Wow, what a quick response, thanks!

In my opinion is very confusing. The way I thought about it, was: 
* `--trimwhitespace always` will trim all orphaned spaces
* `--trimwhitespace nonblank-lines` is a subset of `always` and will trim **only** spaces at the end of the lines

Imagine you are working in the team, and you need to correct something in a file. It is actually good to have trimmed all spaces at the end of the line because they aren't so many. But it is not good to have all blank lines be filled with spaces after swiftformat. If you make a PR with that file, you will have a lot of changes (I know, you can switch whitespaces changes off) even when you make a small change in the file.

Moreover `--trimwhitespace` should _trim_, not _add_ something to the code ;)

**Comment by nicklockwood** [comment] 2017-09-07 21:08
@castus I seem to have done a bad job of explaining.

`--trimwhitespace` works as you describe, but `--trimwhitespace` is not the only function of SwiftFormat.

By default, SwiftFormat applies indenting to the entire file, which includes blank lines. It is the indent function that is adding the space to the line in your example.

If you disable indenting, the space will not be added, e.g:

    > swiftformat --trimwhitespace nonblank-lines --disable indent somefile.swift

**Comment by castus** [comment] 2017-09-09 14:42
@nicklockwood you have amazing response time, thanks ! :)
 
Now I understand, so the indent is the problem here. But I don't want to disable it, because the indent is the most helpful thing of swiftformat ;)
 
Could you please consider to change the behaviour of trimwhitespace, so that when the line is completely empty it won't add spaces to it?

**Comment by nicklockwood** [comment] 2017-09-09 14:57
Why is it that you don't just use `--trimwhitespace always`? Do you have blank lines containing whitespace that you don't want to remove?

**Comment by castus** [comment] 2017-09-09 16:47
Yes, exactly. I'm working in a team where we don't have strong agreement on remove all whitespaces from blank lines. Even Xcode's default settings allows you do to it. So, I would like to use swiftformat for my code, but I don't want to change everything in the file, because PR will be messy then. For now I just disabled that rule using `--disable trailingSpace` but it would be great if I can use. Did I explain it clearer now?

**Comment by castus** [comment] 2017-09-21 09:46
It turns out, that `--disable trailingSpace` is not enough, I must disable `indent` also. It looks like totally weird thing to do, I need to disable indent when I don't want spaces 0_O

**Comment by nicklockwood** [comment] 2017-09-21 09:55
I'm not sure why this is so confusing.

The `indent` rule adds or removes space at the beginning of each line, including blank lines. The `trailingSpace` rule removes the space at the end of each line, including blank lines.

I'm looking into how I can fix this for you at the moment, but it's not clear to me what the expected behavior should be.

If I want blank lines to match the indent of the surrounding code (which some users do), it is natural for that to be inserted by the `indent` rule, since that rule has the context of how much space should be added. I might need to add a separate configuration option for it.

**Comment by castus** [comment] 2017-09-21 15:55
I will write what is my way of thinking:

About `indent` rule, I thought that it will *only* indent my code. So it will change indentation on lines that have some text. It shouldn't change any other lines. That is how I understand indentation.

For ex. I have code:
```
class Foo{
....
....
....
....func bar() {
......let baz = "Baz"
.........}
....
....
}
```

it will make it:
```
class Foo{
....
....
....
....func bar() {
........let baz = "Baz"
....}
....
....
}
```

Second thing is whitespaces. This is something very different than indentation and shouldn't have anything in common. Whitespaces is how Formatter treat whitespaces in the code. Assume I have that code:

```
class Foo{....
....
....
....
....func bar() {..
........let baz = "Baz".....
........}........
....
....
}
```

`--trimwhitespace always`
```
class Foo{



....func bar() {
........let baz = "Baz"
........}


}
```

`--trimwhitespace nonblank-lines`
```
class Foo{
....
....
....
....func bar() {
........let baz = "Baz"
........}
....
....
}
```

Together with indent:
`--trimwhitespace nonblank-lines --indent`
```
class Foo{
....
....
....
....func bar() {
........let baz = "Baz"
....}
....
....
}
```

`--trimwhitespace always --indent`
```
class Foo{



....func bar() {
........let baz = "Baz"
....}


}
```

Does that make sense?

**Comment by castus** [comment] 2018-04-29 19:49
Does that make sense? ;)

**Comment by nicklockwood** [comment] 2020-08-03 21:40
@castus fixed in 0.52.3.

**Closed by nicklockwood** 2020-08-03 21:40 UTC
Labels: enhancement, fixed in develop

**Comment by grigorye** [comment] 2020-09-26 01:42
Just an opinion, but I would love to see an option to enable the original behavior (i.e. "reindenting whitespace"), as it matches what Xcode does by default (that is, with trimming trailing whitespace *disabled* for empty lines) with e.g. Editor > Structure > Reindent (Ctrl-I). I'm basically looking for a formatter that indents exactly like (default) Xcode, and I consider this a "feature" rather than a "bug".

**Comment by nicklockwood** [comment] 2020-09-26 10:24
@grigorye it would certainly make sense for the --xcodeindentation option to enable this behavior.

**Comment by DanDolog** [comment] 2024-04-01 12:00
> Just an opinion, but I would love to see an option to enable the original behavior (i.e. "reindenting whitespace"), as it matches what Xcode does by default (that is, with trimming trailing whitespace _disabled_ for empty lines) with e.g. Editor > Structure > Reindent (Ctrl-I). I'm basically looking for a formatter that indents exactly like (default) Xcode, and I consider this a "feature" rather than a "bug".

@nicklockwood Hi, is there any news on this idea? It's very strange that there is no such option...

**Comment by npip99** [comment] 2024-09-16 22:20
@nicklockwood Hello, would also like to bump this.

The original message from castus,
> Expected behaviour is that it will only trim spaces from lines, that aren't blank. It definitely shouldn't add new spaces to existing code ;)

bothers me quite a bit. (No offense to castus)

My main goal for a formatter is to enforce a canonical format of the code. Similar to python's `black` or go/rust's formatters.

I.e., it really definitely should be adding new spaces to existing code if they weren't already there. Something like an `--xcodeindentation` option to enforce such behavior would be ideal.
