### ISSUE TITLE
`redundantStaticSelf` removes required `Self` in extensions.

### ISSUE THREAD

**Issue by lhunath** [nicklockwood/SwiftFormat#1510] opened 2023-08-17 23:12 UTC
Consider:
```
public extension ButtonStyle where Self == RoundedButtonStyle {
    static func hsRounded(style: Self.Style = .plain) -> Self {
        Self(style: style)
    }
}
public struct RoundedButtonStyle: ButtonStyle {
    public var style:         Style

    public enum Style {
        case plain
    }

    public func makeBody(configuration: Configuration) -> some View {
        EmptyView()
    }
}
```

SwiftFormat's latest `redundantStaticSelf` rule causes `Self.Style = .plain` to be rewritten as `Style = .plain`. However, this results in invalid code since now `Style` cannot be resolved anymore, the `Self` reference is required in this case. This leads to the formatter breaking legal code.

```
$ swiftformat --version
0.52.0
```

**Comment by nicklockwood** [comment] 2023-08-18 00:05
@lhunath I think this is already fixed in 0.52.1

**Comment by lhunath** [comment] 2023-08-18 01:14
oh - I'll try again when `brew` updates.

**Comment by soranoba** [comment] 2023-08-18 04:25
Hi, 0.52.1 is broken.

```
  1> class A { static let defaultName = "A"; let name: String; init() { name = Self.defaultName } } 
  2> class A { static let defaultName = "A"; let name: String; init() { name = defaultName } } 
expression failed to parse:
error: repl.swift:2:75: error: static member 'defaultName' cannot be used on instance of type 'A'
class A { static let defaultName = "A"; let name: String; init() { name = defaultName } }
                                                                          ^~~~~~~~~~~
                                                                          A.
```

0.52.1 will format (1) to (2), so it failed to compile.

**Comment by guillaumealgis** [comment] 2023-08-18 10:44
I'm seeing this too in our project (0.52.1 removing `Self.` where it shouldn't), but I'm struggling to reproduce in a simple out-of-project file.

Will keep you updated if I can repro.

**Comment by vgorloff** [comment] 2023-08-18 11:59
+1 on our side.

Formatting causes removal of the `Self` in expression `guard let value = Self.location(for: warnRegion) ...` which causes compile error.

Here is our code before formatting:

```swift
public class LocationDeeplink: Deeplink {

   convenience init?(warnRegion warnRegionParameter: String) {

      guard let value = Self.location(for: warnRegion) else {
         return nil
      }
      self.init(location: value)
   }
}

extension LocationDeeplink {

   private static func location(for warnRegion: String) -> WCOMLocation? {
      return ...
   }
}
```

**Comment by nicklockwood** [comment] 2023-08-18 15:13
@soranoba I wasn't able to reproduce your issue with 0.52.1, but I was able to reproduce it with 0.52.0. Are you sure you're on the latest? Run `swiftformat --version` if you aren't sure.

**Comment by nicklockwood** [comment] 2023-08-18 15:14
@vgorloff this is a different, but related bug. I'll fix it for the next release.

**Comment by nicklockwood** [comment] 2023-08-18 15:16
@guillaumealgis if you are able to repro, please open a separate ticket. If you are able to share the entire file or some significant chunk of it, that will be fine - it doesn't need to compile.

**Comment by soranoba** [comment] 2023-08-18 15:26
I use 0.52.1, but it does not happend to bug with this code. Sorry...
Attached is the code from when it actually happened.

```swift
public struct Attributes: OptionSet, Decodable {
    public let rawValue: UInt

    public init(rawValue: UInt) {
        self.rawValue = rawValue
    }

    public init(from decoder: Decoder) throws {
        var container = try decoder.unkeyedContainer()
        var result: Attributes = []
        while !container.isAtEnd {
            let name = try container.decode(String.self)
            if let type = Self.mapping[name] { // <--- here
                result.insert(type)
            }
        }
        self = result
    }

    private static let mapping: [String: Attributes] = [
    ]
}
```

**Comment by soranoba** [comment] 2023-08-18 15:32
And it reproduced. The if statement may be suspicious.
```swift
public class Store {
    private static let kUserName: String? = "USER_NAME"

    @objc lazy var userName: String = {
        if let name = Self.kUserName {
            return name
        }
        return ""
    }
}
```

**Comment by nicklockwood** [comment] 2023-08-18 16:56
@soranoba OK cool, it seems to be the same issue as @vgorloff's. Basically it happens if `Self` is used inside `let` or `if/guard let` expressions.

**Comment by FelixLisczyk** [comment] 2023-08-19 07:49
Version 0.52.2 fixes this issue in my project. Thank you! 👍

**Comment by soranoba** [comment] 2023-08-21 02:36
Version 0.52.2 fixes my issue too. Thanks!!

**Closed** 2023-08-21 02:37 UTC
Labels: bug, fixed in develop

**Comment by danielga** [comment] 2023-08-24 11:50
Still have a few cases creating issues on 0.52.2.
Made a small example to showcase it, where we use `swift-composable-architecture` and `xctest-dynamic-overlay`.

```swift
public func XCTUnimplemented<Result>(
    _ path: KeyPath<some Any, some Any>,
    file: StaticString = #file,
    fileID: StaticString = #fileID,
    line: UInt = #line
) -> @Sendable () -> Result {
    return { fatalError("don't care") }
}

public struct Environment {
    let test: () -> Void

    init(test: @escaping () -> Void) {
        self.test = test
    }

    static var unimplemented: Self {
        .init(test: XCTUnimplemented(\Self.test)) // this `Self` is removed by SwiftFormat, but is necessary
    }
}
```

**Comment by lucianopa-msft** [comment] 2023-08-29 18:09
Hi we are also seeing few extra cases where `Self` is still in 0.5.2 being removed incorrectly:
```swift
class A {
    static var p: Int = 0
}

class B: A {
    var test: Int {
        return Self.p.bitWidth // Still being removed
    }
}
```
