### ISSUE TITLE
Placeholder for 3 possible Issues

### ISSUE THREAD

**Issue by garricn** [nicklockwood/SwiftFormat#193] opened 2017-11-22 07:10 UTC
### Test file: `test.swift`

**Test Case 1**

File contains:

```
let abc =
        """
        one \
        two
        """
```

Running `$ swiftformat test.swift` results in:

```
let abc =
    """
    one \"
    two
    """
```

**Test Case 2**

File contains: 

```
func test() {
//    print("test")
}
```

Running `$ swiftformat test.swift --comments ignore` results in:

```
func test() {
    //    print("test")
}
```

**Test Case 3**

File contains: 

```
func test() {
    print(123_456.123_456)
}
```

Running `$ swiftformat test.swift --decimalgrouping "3,0"` results in:

```
func test() {
    print(123_456.123456)
}
```

**Comment by nicklockwood** [comment] 2017-11-22 23:25
@garricn 

Case 1 is definitely a bug - not the indenting, but the extra " that was inserted

Case 2 is by design. The --comments ignore feature is designed to disable indenting of multiline comments, because these sometimes contain code samples that shouldn't be re-indented.

I guess in this case you wanted to disable indenting of commented-out code? Unfortunately there's no feature for that at the moment.

Case 3 is also by design - I've never seen anyone using grouping for fraction digits before. It's not a common practice as far as I know, but if you need it then I can look into implementing it.

**Comment by garricn** [comment] 2017-11-24 03:51
Thank you! I’ll relay this info to my team :)

**Comment by nicklockwood** [comment] 2017-11-24 22:59
@garricn I've just release SwiftFormat 0.31.0 which fixes issues 1 and 2. I don't consider issue 3 to be a bug, so I'm going to close this now, but feel free to reopen if you have additional info.

**Closed by nicklockwood** 2017-11-24 22:59 UTC

**Comment by nicklockwood** [comment] 2017-11-24 23:00
@garricn I forgot to mention - the fix for commented-out code doesn't require the `--comments ignore` flag to be set, so you can remove that unless you have multiline comment blocks that you also wish to be ignored.
