### ISSUE TITLE
Removing necessary explicit reference to self in autoclosures.

### ISSUE THREAD

**Issue by jarsen** [nicklockwood/SwiftFormat#126] opened 2017-04-05 20:13 UTC
I've got some regular ol' XCTestCases using matchers from Nimble. The Nimble `expect` function uses an autoclosure to get its `expect(foo) == bar` style matchers. However, with the redundant self option on, SwiftFormat doesn't seem to realize that the reference to self is necessary to make the capture semantics explicit and removes it, resulting in code that no longer compiles.

In other words

```swift
class FooTests: XCTestCase {
    let foo = 1

    func testFoo() {
        expect(self.foo) == 1
    }
}
```

turns into

```swift
class FooTests: XCTestCase {
    let foo = 1

    func testFoo() {
        expect(foo) == 1
    }
}
```

Which results in the error `Reference to property 'foo' in closure requires explicit 'self.' to make capture semantics explicit.`

**Comment by nicklockwood** [comment] 2017-04-05 20:17
Hmm. I don't think there's any way I can detect that. Darn.

I'll see if I can think of a solution. In the meantime, you'll probably have to use `--disable redundantSelf`

**Comment by jarsen** [comment] 2017-04-05 20:41
Yeah, I was thinking about how difficult it would be to detect autoclosures. But you are a wizard 🔮 so you never know. 😛 

Disabling the redundant self is the current game plan. Either that or not using Nimble. Or using Quick instead of XCTestCase. I'll figure something out.

Anyway, feel free to close this if there's no good solution, just thought I'd throw the issue out there since I didn't see anything about it already. Thanks for you hard work! Love the tool. ❤️

**Comment by Rerel** [comment] 2017-04-19 07:34
I'm having a similar issue with the necessary self with this scenario:

```
DispatchQueue.main.async {
  do {
     value = try self.getValue()
     completionClosure(value)
  } catch let error as NSError {
     ...
  }
}
```

turns into

```
DispatchQueue.main.async {
  do {
     value = try getValue()
     completionClosure(value)
  } catch let error as NSError {
     ...
  }
}
```

Which gives me a `Call to method 'getValue' in closure requires explicit 'self.' to make capture semantics explicit`

I'm going to use `--disable redundantSelf` for now.

**Comment by nicklockwood** [comment] 2017-04-19 07:58
@Rerel that looks like a more straightforward bug - I should be able to fix it.

**Comment by nicklockwood** [comment] 2017-04-19 08:18
@Rerel are you using SwiftFormat 0.28.2? I'm having trouble reproducing your bug.

**Comment by Rerel** [comment] 2017-04-19 08:27
@nicklockwood Yes I'm using SwiftFormat 0.28.2.

 My bad I didn't detail exactly the issue, try with: 

```
        DispatchQueue.global(qos: DispatchQoS.QoSClass.default).async {
            do {
                value = try self.getValue()
                ...
            } catch let s as NSError {
                ...
            }
        }
```

**Comment by nicklockwood** [comment] 2017-04-20 20:53
@Rerel fixed in 0.28.3

**Comment by nicklockwood** [comment] 2017-11-20 00:05
@jarsen This is fixed in 0.30.2. I've just added a special case for `expect()`, since the Nimble framework is the only place where this issue has arisen so far.

**Comment by little-bamboo** [comment] 2018-09-10 18:16
Did this issue creep back into the latest release (0.35.5)?  

Formatting using swiftformat is now removing references to self, causing warnings for all variables.  

    import Foundation

    class GameData: NSObject, NSCoding {   

        var easyDifficulty: Bool {
            get {
                return **self.**easyDifficulty
            }
            set(setEasyDifficulty) {
                **self**.easyDifficulty = setEasyDifficulty
            }
        }

    **(AFTER SWIFTFORMAT)**

        var easyDifficulty: Bool {
            get {
                return easyDifficulty
            }
            set(setEasyDifficulty) {
                easyDifficulty = setEasyDifficulty
            }
        }

Warning: Attempting to modify 'easyDifficulty' within its own setter
Version: swiftformat, version 0.35.5
XCode: v9.4.1

**Comment by nicklockwood** [comment] 2018-09-10 19:06
@little-bamboo I’ve not encountered this particular scenario before so it’s possible it was never handled correctly. I’d be surprised if the bug was introduced in the latest release as that was just a bug fix for an unrelated issue.

I’ll investigate a fix.

**Comment by nicklockwood** [comment] 2018-09-10 20:47
@little-bamboo in trying to replicate this I realized that the code example you provided creates an infinite loop and crashes if you try to set or get the property:

```swift
var easyDifficulty: Bool {
        get {
            return self.easyDifficulty
        }
        set(setEasyDifficulty) {
            self.easyDifficulty = setEasyDifficulty
        }
    }
```

It seems like it might be a bug that it compiles at all, because calling the getter inside the getter and the setter inside the setter would always result in an infinite recursion (even if you use `self`).

I assume this wasn't your actual code - do you have a legitimate example?

**Comment by little-bamboo** [comment] 2018-09-10 21:06
My apologies.  Once I initialized the variables the error went away, sorry for the confusion!

**Comment by nicklockwood** [comment] 2018-09-10 21:09
@little-bamboo no problem - I found another bug while investigating yours, so it was helpful after all :-)

**Closed by nicklockwood** 2018-09-10 21:09 UTC

**Comment by laszloagardi** [comment] 2020-12-17 09:56
This bug also appears when creating `OSLogMessage` messages with string interpolation using instance variables.
Example:

```swift
import os.log

class LogDemo {
    let logger = Logger(subsystem: "sub", category: "cat")
    let foo = "foo"
    func log() {
        // BUG: self should not be removed but it is removed
        logger.debug("bug here: \(self.foo)")
    }
}
```

**Comment by nicklockwood** [comment] 2020-12-17 10:54
@laszloagardi I believe you can solve this by adding `--selfrequired debug` to the SwiftFormat arguments. This tells SwiftFormat that the `debug()` function has autoclosure arguments and should not have `self` removed.

(ps, it's best to open a new issue when reporting a new bug, as it's easy for me to miss comments on closed issues.)

**Comment by drekka** [comment] 2021-08-01 11:23
Don't know if it's logged anywhere else, but I've been doing log messages like this:
```swift
os_log(.debug, "My message with \(self.someValue)")
```

Which necessitated using `--selfrequired os_log`
