### ISSUE TITLE
Swiftformat 0.48.18 indentation rules changed (?)

### ISSUE THREAD

**Issue by psiwork** [nicklockwood/SwiftFormat#1074] opened 2021-11-11 12:24 UTC
When I updated SwiftFormat to 0.48.18 and run it, I have got a tons of new fixes, most of them with an indentations. 
The issue is: now it conflicting with Xcode's own indentation rules. 

I attached the screenshot below with the changes being proposed by Swiftformat. Looks like it tries to align with the closing bracket ```}```. But Xcode always keeps the indentations to distinguish between the code blocks. 
We discussed with the team and it's not obviously good idea: looks better but readability suffers.

Is it a intentional change or a kind of bug of SwiftFormat?

![Screenshot 2021-11-11 at 12 12 37](https://user-images.githubusercontent.com/91961396/141288692-60eb3c94-4b00-4bfc-a4c3-10ff5281c43d.png)

**Comment by timstudt** [comment] 2021-11-11 12:55
I can see why it's aligned with closing brackets, but especially in `SwiftUI` this decreases readability IMO.
```swift
struct SomeView: View {
    var body: some View {
        Button("1", action: {
            /* */
        })
        .padding(10)  // swiftformat
        Button("2", action: {
            /**/
        })
    }
}
```
```swift
struct SomeView: View {
    var body: some View {
        Button("1", action: {
            /* */
        })
            .padding(10)  // Xcode default
        Button("2", action: {
            /**/
        })
    }
}
```
even with  ` --wraparguments before-first` and `--wrapparameters before-first` it's harder to read:

```swift
struct SomeView: View {
    var body: some View {
        Button(
            "1",
            action: {
                /* */
            }
        )
        .padding(10) // aligns with closing bracket ')'
        Button(
            "2",
            action: {
                /**/
            }
        )
    }
}
```
when using trailing closures it looks fine
```swift
struct SomeView: View {
    var body: some View {
        Button(
            "1") {
                /* */
            }
            .padding(10) // <- indented
        Button(
            "2",
            action: {
                /**/
            }
        )
    }
}
```

I feel that `)` should not be handled the same way as `}` but rather indent the old way.

**Comment by nicklockwood** [comment] 2021-11-11 15:45
Hmm, this was always the intended behavior, but due to a bug wasn't always enforced before.

It may have other side-effects that you don't want, but have you tried using `--xcodeindentation true`? This enables a mode where swiftformat indenting behaves more like Xcode's defaults.

If that doesn't solve your issue, I'll consider adding another option just to control this case.

**Comment by timstudt** [comment] 2021-11-11 15:50
@nicklockwood  `--xcodeindentation true` works as expected. thx

**Closed** 2021-11-11 16:03 UTC
