### ISSUE TITLE
Add an Option to indent method's closing brace if the last param is an array or closure

### ISSUE THREAD

**Issue by rjchatfield** [nicklockwood/SwiftFormat#187] opened 2017-10-31 11:07 UTC
Current indent output:

```swift
return f(
    block: {
        statement
})
return f(
    array: [
        element,
])
```

It would be great to have an option to indent this like below:

```swift
return f(
    block: {
        statement
    })
return f(
    array: [
        element,
    ])
```

Suggestion:
```bash
swiftformat . --danglingparen "indent"
```

**Comment by nicklockwood** [comment] 2017-11-08 12:11
The issue is that the ( and { have separate indents, but the } and ) have the same indent. SwiftFormat tries to match the outermost indent in this situation. If you write it like this instead, it looks better:

```swift
return f(
    block: {
        statement
    }
)
return f(
    array: [
        element,
    ]
)
```

**Comment by rjchatfield** [comment] 2017-11-08 13:24
Thanks for replying. That’s what we defaulted to. Well, a mixture of all 3. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicklockwood** [comment] 2020-01-07 18:31
@rjchatfield this now works in a better way. With the default settings you get this:

```swift
return f(
    block: {
        statement
    }
)
return f(
    array: [
        element,
    ]
)
```

with `--closing-paren` you get this, which IIUC is what you wanted for array, but still isn't quite right for closures:

```swift
return f(
    block: {
        statement
})
return f(
    array: [
        element,
    ])
```

**Comment by nicklockwood** [comment] 2020-07-30 22:37
@rjchatfield this is now the default behavior in version 0.45.0.

**Closed by nicklockwood** 2020-07-30 22:37 UTC
