### ISSUE TITLE
Inconsistent results formatting functions with "wrapMultilineStatementBraces" enabled

### ISSUE THREAD

**Issue by johnclayton** [nicklockwood/SwiftFormat#1115] opened 2022-01-11 21:23 UTC
Hello. I'm running into some inconsistencies with "wrapMultilineStatementBraces" A function like this:

```
func aFunc(
    one: Int,
    two: Int) -> String {
    "one"
}
```

will produce this:

```
func aFunc(
    one: Int,
    two: Int
) -> String
{
    "one"
}
```

Which seems to be the intent. But this:

```
func aFunc(
        one: Int,
        two: Int
) -> String {
    "one"
}
```

will not have the trailing brace wrapped. It will remain unchanged, which seems to contradict the rule.

**Comment by nicklockwood** [comment] 2022-01-14 11:58
@johnclayton thanks for reporting. This looks like a bug. The behavior seems to depend on the order in which two different rules are applied, which is why it's not behaving consistently.

**Comment by calda** [comment] 2022-01-15 19:12
> Hello. I'm running into some inconsistencies with "wrapMultilineStatementBraces" A function like this:
> 
> ```
> func aFunc(
>     one: Int,
>     two: Int) -> String {
>     "one"
> }
> ```
> 
> will produce this:
> 
> ```
> func aFunc(
>     one: Int,
>     two: Int
> ) -> String
> {
>     "one"
> }
> ```

I think this was a bug. On `develop`, which includes a bunch of fixes to this rule from #1071, 

```swift
func aFunc(
    one _: Int,
    two _: Int) -> String {
    "one"
}
```

is reformatted to

```swift
func aFunc(
    one _: Int,
    two _: Int
) -> String {
    "one"
}
```

**Comment by calda** [comment] 2022-01-15 19:12
Added tests that demonstrate this behavior in #1123

**Comment by nicklockwood** [comment] 2022-01-26 21:51
@johnclayton on further investigation, this is actually expected behavior. The `wrapMultilineStatementBraces` rule on its own, will not convert this:

```swift
func aFunc(
    one: Int,
    two: Int
) -> String {
    "one"
}
```

to this

```swift
func aFunc(
        one: Int,
        two: Int
) -> String
{
    "one"
}
```

This is not actually the preferred formatting style because the purpose of the rule is to ensure bodies can be distinguished from arguments, and in the above example there's no confusion, whereas here there is due to the closing paren position:

```swift
func aFunc(
    one: Int,
    two: Int) -> String {
    "one"
}
```

The decision about whether the closing `)` should be wrapped to the next line is handled by the `wrapArguments` rule. If you enable that rule as well and set the `--closingparen` option, then the formatting behaves self-consistently.

**Closed** 2022-02-09 15:12 UTC
Labels: not a bug
