### ISSUE TITLE
Binding param replace with _

### ISSUE THREAD

**Issue by filimo** [nicklockwood/SwiftFormat#1309] opened 2022-11-14 08:55 UTC
I face with an issue when a binding param **$item** replace with **_** on swiftformat 0.50.3

before:
```swift
private var listView: some View {
    List($service.widgets, id: \.sysObjectId) { $item in
        Text(item.description())
    }
}
```
    
after:
```swift
private var listView: some View {
    List($service.widgets, id: \.sysObjectId) { _ in
        Text(item.description())
    }
}
```

**Comment by nicklockwood** [comment] 2022-11-14 09:12
@filimo I'm not able to reproduce this with the sample you've provided. It might be dependent on some other code in the file, or your particular .swiftformat configuration. Can you share the whole file, or a standalone sample demonstrating the problem?

**Comment by filimo** [comment] 2022-11-16 09:36
> @filimo I'm not able to reproduce this with the sample you've provided. It might be dependent on some other code in the file, or your particular .swiftformat configuration. Can you share the whole file, or a standalone sample demonstrating the problem?

You can reproduce this issue to create a new  project with following code:

```swift
import SwiftUI

class SomeService: ObservableObject {
    @Published var widgets: [String] = []
}

struct ContentView: View {
    @StateObject var service = SomeService()
    
    var body: some View {
        List($service.widgets, id: \.self) { $item in
            Text(item)
        }
    }
}
```

**Comment by nicklockwood** [comment] 2022-11-23 12:10
@filimo when I run swiftformat 0.50.3 on a file containing just this code it reports no changes. It is somehow possible that you have an older version installed? What do you get when you run `swiftformat --version`?

**Comment by Jerry-Wang-Developer** [comment] 2023-01-07 17:34
Hi, @nicklockwood  I found the reproduce way. 
You can add some codes that make compile errors, and the bug appear.
Such as, add some codes after 
```
    @StateObject var service = SomeService() xxxx
```
and build again, the $item will be replace with _
My Xcode version is 14.0 and swift version is 5.7.2

**Comment by Jerry-Wang-Developer** [comment] 2023-01-07 17:42
It seems that my swiftformat version is lower than 0.50.3.

But when I try to update my swiftformat on mac (MacOS 13), it failed.

 ~ % brew upgrade swiftformat
Warning: You are using macOS 13.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

Warning: swiftformat 0.47.12 already installed

**Comment by nicklockwood** [comment] 2023-01-07 19:16
Try running `brew update` first - if you have an outdate copy of brew it may not be aware of the latest version

**Closed** 2023-01-29 14:41 UTC
Labels: can't reproduce
