### ISSUE TITLE
Can I set up blankLinesAtStartOfScope?

### ISSUE THREAD

**Issue by mefilt** [nicklockwood/SwiftFormat#274] opened 2018-07-16 11:17 UTC
I do not want to delete the space before the type

Before SwiftFormat
```
struct Environment: Decodable {

    struct AssetInfo: Decodable {

        let assetId: String
        let name: String
        let quantity: Int64
        let decimals: Int
    }
}
```

After SwiftFormat
```
struct Environment: Decodable {
    struct AssetInfo: Decodable {
        let assetId: String
        let name: String
        let quantity: Int64
        let decimals: Int
    }
}
```
Want space between types

After SwiftFormat
```
struct Environment: Decodable {

    struct AssetInfo: Decodable {
        let assetId: String
        let name: String
        let quantity: Int64
        let decimals: Int
    }
}
```

Thx

**Comment by nicklockwood** [comment] 2018-07-24 22:17
This seem to be a duplicate of https://github.com/nicklockwood/SwiftFormat/issues/261

**Closed** 2020-08-09 06:51 UTC
