### ISSUE TITLE
Illegal instruction: 4 error in version 0.43.5

### ISSUE THREAD

**Issue by timbms** [nicklockwood/SwiftFormat#532] opened 2020-01-14 06:13 UTC
I see a similar pattern to #331 when running the version installed via cocoapods

> ${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat --verbose . 
 
I get the following error 
....
```
Formatting /Users/tms/Developer/openhab/openhab-develop-20191117/openHABWatchSwift Extension/openHABWatch Extension/app/AppConstants.swift
Illegal instruction: 4
```

Seems to be related to all small files with <10 lines of code

**Comment by nicklockwood** [comment] 2020-01-14 07:21
@timbms thanks for reporting this - could you share an example file that demonstrates the issue?

**Comment by timbms** [comment] 2020-01-14 17:54
Here is an example file
[charStyle.zip](https://github.com/nicklockwood/SwiftFormat/files/4060592/charStyle.zip)

**Comment by nicklockwood** [comment] 2020-01-14 21:22
I'm not able to reproduce this with 0.43.5 and the swift file you sent. Could there be some other factor involved?

**Comment by nicklockwood** [comment] 2020-01-14 21:24
I tested using the homebrew install with the following command:

```bash
$ swiftformat ~/Downloads/openHAB/ChartStyle.swift --verbose
```

Does that also reproduce the error for you, or does it have to be a Cocoapods install?

**Comment by timbms** [comment] 2020-01-15 05:27
Homebrew install is indeed without error. Problem occurs only with cocoapods install

**Comment by nicklockwood** [comment] 2020-01-15 23:27
@timbms I believe this should be fixed in 0.44.0. Please verify.

**Comment by timbms** [comment] 2020-01-18 16:12
0.44.0 still shows the same error with installation by cocoa pods
How could I trace this further?

**Comment by timbms** [comment] 2020-01-19 15:21
I played with the .swiftformat file. 
The offending rule seems to be the last line with the attached .swiftformat file. If I comment out the header file, everything runs smoothly. 
Just changed filename to swiftformat.txt to make it uploadable on GitHub
[swiftformat.txt](https://github.com/nicklockwood/SwiftFormat/files/4082835/swiftformat.txt)

**Comment by nicklockwood** [comment] 2020-01-26 16:55
@timbms thanks for digging into this. It should now be fixed in 0.44.1.

**Closed by nicklockwood** 2020-01-26 16:55 UTC
