### ISSUE TITLE
SwiftFormat adds a comma at the end of array

### ISSUE THREAD

**Issue by 3lvis** [nicklockwood/SwiftFormat#49] opened 2016-10-17 20:15 UTC
#### Example
<img width="524" alt="screen shot 2016-10-17 at 22 13 15" src="https://cloud.githubusercontent.com/assets/1088217/19453843/36611d08-94b7-11e6-91bc-26549d34d10e.png">

**Comment by nicklockwood** [comment] 2016-10-17 22:00
This is by design. It's good practice because it means that if you add extra lines, the last line isn't marked as modified in a git commit.

**Closed** 2016-10-17 23:43 UTC

**Comment by 3lvis** [comment] 2016-10-18 08:10
Makes sense, thanks!

**Comment by nicklockwood** [comment] 2016-10-21 21:47
FYI, trailing commas can now be disabled.

**Comment by 3lvis** [comment] 2016-10-22 09:22
Thanks!

**Comment by rx2130** [comment] 2017-02-28 15:56
I suppose this rule should be default disabled. As [Allow trailing commas in parameter lists and tuples](https://github.com/apple/swift-evolution/blob/master/proposals/0084-trailing-commas.md) was rejected in Swift 3.

**Comment by nicklockwood** [comment] 2017-02-28 16:00
@rx2130 the proposal to allow trailing commas in parameter lists was rejected, but they didn't removed support for them in array and dictionary literals. SwiftFormat only adds them in the places where they are allowed (unless you've found a bug).
