### ISSUE TITLE
Issue with `async let _ = …` for void type

### ISSUE THREAD

**Issue by paxos** [nicklockwood/SwiftFormat#1255] opened 2022-08-23 17:49 UTC
Example:

```
async let _ = try await funcReturningVoid()
```

This snippet compiles without a warning on Xcode 13.4

Is getting formatted to:

```
async _ = try await funcReturningVoid()
```

which is not compiling anymore.

Is this a bug or is there a configuration value for this somewhere?

**Comment by nicklockwood** [comment] 2022-08-23 20:02
This is a bug - thanks for flagging it

**Comment by nicklockwood** [comment] 2022-08-23 20:09
This is caused by the `redundantLet` rule, so disabling that should be a workaround for now.

**Comment by paxos** [comment] 2022-08-23 20:17
Thanks!

Also, fantastic project: I could not do my work without this anymore <3

**Comment by nicklockwood** [comment] 2022-08-30 20:39
@paxos Fixed in 0.49.18

**Closed by nicklockwood** 2022-08-30 20:39 UTC
Labels: bug, fixed in develop

**Comment by paxos** [comment] 2022-08-30 20:56
Thanks, thats amazing 🚀
