### ISSUE TITLE
Command line tool fails to compile/run: dyld not found in "formatCode" build phase, image not found

### ISSUE THREAD

**Issue by bgalamb** [nicklockwood/SwiftFormat#412] opened 2019-04-10 18:59 UTC
I have checked out the latest tag 0.40.5. I tried to compile the target SwiftFormat (Command line tools) but it fails. It looks like there is an issue in the formatCode phase of the build. The command "${SRCROOT}/format.sh" fails with:
`dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/i040023/com.sap.mobile.platform.client.oss.ios.swiftformat/src/CommandLineTool/swiftformat
  Reason: image not found
/Users/i040023/com.sap.mobile.platform.client.oss.ios.swiftformat/src/format.sh: line 3:  4077 Abort trap: 6           CommandLineTool/swiftformat . --cache ignore
Command PhaseScriptExecution failed with a nonzero exit code`

Xcode is 10.2
os: 10.14.3

**Comment by nicklockwood** [comment] 2019-04-10 19:15
@bgalamb have you tried `Product > Clean Build Folder`? It might be a transient issue.

Also, is there a particular reason why you're trying to build the CLI from source - is the binary in the repo not working on your machine?

**Comment by nicklockwood** [comment] 2019-04-10 19:17
@bgalamb it should be safe to just disable/remove the formatCode script. All it does is run the local binary copy of swiftformat.

**Comment by bgalamb** [comment] 2019-04-11 07:27
removing the formatCode phase would solve the symptom, but the binaries that are produced after the Xcode build are having the same error:
`
ZZZM34191728A:com.sap.mobile.platform.client.oss.ios.swiftformat i040023$ find . -name swiftformat
./gen/out/Build/Products/Release/swiftformat
./gen/out/Build/Products/Release/swiftformat.dSYM/Contents/Resources/DWARF/swiftformat
./gen/out/Build/Products/Debug/swiftformat`

`$ >
./gen/out/Build/Products/Release/swiftformat
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/i040023/com.sap.mobile.platform.client.oss.ios.swiftformat/./gen/out/Build/Products/Release/swiftformat
  Reason: image not found
Abort trap: 6
`

If I use the CLI command `swift build -c release` then the binary which is created is ok. (as WA I am using this now).
It looks like the above error is got when I do it the compile from Xcode directly.

**Comment by MaxDesiatov** [comment] 2019-04-11 10:19
I'm having kind of a similar issue when installing SwiftFormat on Travis via `brew install swiftformat` on `xcode10.2` image (which is Mojave 10.14.4 that assumes you're linked with the stdlib available in the system I guess?)

```
$ swiftformat --lint --verbose .
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /usr/local/bin/swiftformat
  Reason: image not found
```

**Comment by nicklockwood** [comment] 2019-04-11 10:27
@MaxDesiatov strange. That explanation makes sense, but I'm running 10.14.4 with Xcode 10.2 and had no problem installing swiftformat 0.40.5 via `brew upgrade`, so I'm not sure what would be different about your travis setup :-/

**Comment by MaxDesiatov** [comment] 2019-04-11 11:14
This is a simple bare-bones .travis.yml that reproduces this:

```yaml
osx_image: xcode10.2
language: swift
script:
  - brew update
  - brew install swiftformat
  - swiftformat --version
```

The test repository is available [here](https://github.com/MaxDesiatov/SwiftFormatTravis) and the failing build is [this one](https://travis-ci.com/MaxDesiatov/SwiftFormatTravis/builds/107946764), but all newer builds are failing too.

**Comment by MaxDesiatov** [comment] 2019-04-11 11:15
This _probably_ started happening with 0.40.6, not 0.40.5. Please let me know if the 0.40.6 `dyld` thing is unrelated and you'd like me to create a separate issue here.

**Comment by MaxDesiatov** [comment] 2019-04-11 11:19
Ok, my current hypothesis is that when you build with Xcode 10.2 and run on 10.14.4 all is fine as it's able to find the system Swift stdlib, but building with Xcode 10.2 and running on 10.14.3 (which is what Travis and OP do) fails because the system Swift stdlib is absent and it's not linked with local stdlib apparently. I hope this can be fixed in the Homebrew formula?

**Comment by nicklockwood** [comment] 2019-04-12 08:42
@MaxDesiatov if your theory is correct, this problem will presumably solve itself fairly quickly as users upgrade. I'm not sure what Travis's policy is on this - I don't see any reason why they wouldn't eventually upgrade, as I'd assume they'd want to always use the latest point release available for a given Xcode version.

**Comment by ochristensen** [comment] 2019-04-16 16:32
we have release cycles that prevent us from upgrading to latest all the time.  we're shipping a product built in xcode 10.1 and we get the same behavior

**Comment by mjl5007** [comment] 2019-04-16 18:47
Per the [Swift 5 Release Notes for Xcode 10.2](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2):
> Swift command line projects won’t run on macOS 10.14.3 and earlier unless you install the Swift 5 Runtime Support for Command Line Tools package. Without that package, Swift command line projects crash on launch with “dyld: Library not loaded” errors. (46824656)

Sounds like that's what happened here.

At the very least, if the system requirements of the distributed binaries have changed (e.g. requires 10.14.4 *or* the **Swift 5 Runtime Support for Command Line Tools** package), then that should be called out explicitly somewhere where people will see it.

That said, not everyone can just upgrade their OS version whenever a new point release comes out, and as @MaxDesiatov has shown it can take a while for tooling to catch up.

**Comment by nicklockwood** [comment] 2019-04-16 19:22
@mjl5007 thanks for the explanation. This was a frustrating choice on Apple's part 😔

I'll add a note to the README, but it doesn't seem like there is much that I can do to fix this for Travis & Homebrew users.

**Comment by MaxDesiatov** [comment] 2019-04-16 19:23
maybe there's a way to install Swift 5 runtime support from command-line that could be added to README?

**Comment by ochristensen** [comment] 2019-04-16 19:44
just installing the "Swift 5 Runtime Support for Command Line Tools" package fixes those that install swiftformat via homebrew on 10.14.3 and earlier.

so just a note (perhaps a very prominent one :)) that it's required would be helpful for most cases.

**Comment by nicklockwood** [comment] 2019-04-16 21:25
I've added a prominent note to the README explaining the workaround. Let me know if there's anything else I can do.

**Closed by nicklockwood** 2019-04-16 21:25 UTC

**Comment by mjl5007** [comment] 2019-04-17 14:37
The binary packages distributed via Homebrew are built automatically by the Brew Test Bot, and not manually by you or someone else, correct?

It's not 100% clear to me whether simply building with Xcode 10.2 is enough for the resultant binary to link to the system-installed Swift runtime rather than including it in the binary, or if there is some setting in the Xcode project that also controls it. I suspect it is the former, simply because I didn't see any changes in the commit history between 0.40.4 and 0.40.5 that look like they would have triggered this change. So it must simply have been a matter of the Brew Test Bot CI machines being upgraded to Xcode 10.2 and/or macOS 10.14.4.

**Comment by nicklockwood** [comment] 2019-04-17 17:02
@mjl5007

> The binary packages distributed via Homebrew are built automatically by the Brew Test Bot, and not manually by you or someone else, correct?

Correct.
