### ISSUE TITLE
When using --maxwidth /// comments that exceed it are replaced with //

### ISSUE THREAD

**Issue by lukelabonte** [nicklockwood/SwiftFormat#1290] opened 2022-10-14 19:57 UTC
If there is a documentation comment that exceeds whatever the `maxwidth` is, when it is broken to a new line, the `///` is replaced with `//`. This is problematic because it then breaks the documentation for whatever was documented. Instead, it would be nice if `maxwidth` perverse the `///`.

**Comment by orchetect** [comment] 2022-10-19 01:04
Have you tried the latest version? This particular issue appears resolved in 0.50.2.

(Previously logged in #1270)

**Comment by nicklockwood** [comment] 2022-10-19 09:52
@lukelabonte yeah, I believe this is already fixed in 0.50.2. There are still some other bugs with comment wrapping, but I can't reproduce this one on the latest release.

**Closed by nicklockwood** 2022-10-19 09:52 UTC
