### ISSUE TITLE
`--xcodeindentation enabled` doesn't match Xcode for after closing parenthesis on its own line

### ISSUE THREAD

**Issue by jgale** [nicklockwood/SwiftFormat#1163] opened 2022-03-29 22:23 UTC
This is what I get from `swiftformat . --xcodeindentation enabled` on 0.49.6:

```swift
    func execute3() -> AnyPublisher<TraceEvent, Never> {
        Publishers.CombineLatest(
            observePlaybackStartEvents(),
            isUserLoggedIn()
        )
            .compactMap {
                .map(playbackStartEvent: $0.0, isLoggedIn: $0.1)
            }
    }

    public var body: some View {
        TextField(
            "Hello, World",
            text: $name
        )
            .textContentType(.givenName)
            .padding()
    }
```

Xcode 13.3 itself will not indent those lines if they come directly after a closing parenthesis on its own line:

```swift
    func execute3() -> AnyPublisher<TraceEvent, Never> {
        Publishers.CombineLatest(
            observePlaybackStartEvents(),
            isUserLoggedIn()
        )
        .compactMap {
            .map(playbackStartEvent: $0.0, isLoggedIn: $0.1)
        }
    }

    public var body: some View {
        TextField(
            "Hello, World",
            text: $name
        )
        .textContentType(.givenName)
        .padding()
    }
```

Notes:
* This is similar/duplicate to https://github.com/nicklockwood/SwiftFormat/issues/1081, but it was unclear to me what action was being requested in that bug. IMO, it's definitely a bug that it doesn't match Xcode with `--xcodeindentation enabled`
* I believe this is a regression, as it didn't do this in `0.48.11`

**Comment by nicklockwood** [comment] 2022-04-03 18:24
@jgale I can confirm that this behavior was explicitly added in 0.48.12, presumably to match the behavior of Xcode at the time. Since Xcode no longer behaves this way I'll update SwiftFormat to match.

**Comment by jgale** [comment] 2022-04-04 14:58
Thank you! And thanks for all you do @nicklockwood.

**Comment by nicklockwood** [comment] 2022-04-04 17:16
@jgale fixed in 0.49.7

**Closed by nicklockwood** 2022-04-04 17:16 UTC
Labels: enhancement
