### ISSUE TITLE
redundantClosure leads to compile error

### ISSUE THREAD

**Issue by alistra** [nicklockwood/SwiftFormat#1236] opened 2022-07-29 10:35 UTC
`redundantClosure` rule leads to a compile error.

This:
```
    static let once: Void = { object_setClass(Bundle.main, type(of: BundleExtension())) }()
```

Gets translated into this:
```
    static let once: Void = object_setClass(Bundle.main, type(of: BundleExtension()))
```

Leading to a type clash of `AnyClass?` not being `Void`

**Comment by nicklockwood** [comment] 2022-07-31 07:45
@alistra this is a known issue that affects methods with `@discardableResult` return values. The workaround is to change the code to:

```swift
static let once: Void = { _ = object_setClass(Bundle.main, type(of: BundleExtension())) }()
```

or add a swiftformat comment directive:

```swift
// swiftformat:disable:next redundantClosure
static let once: Void = { object_setClass(Bundle.main, type(of: BundleExtension())) }()
```

**Comment by nicklockwood** [comment] 2022-07-31 07:49
@alistra apologies, this is not actually mentioned in the list of known issues. I was confusing it with the `redundantVoidReturnType` rule. I'll add a note.

**Comment by nicklockwood** [comment] 2022-07-31 07:55
@calda FYI.

**Comment by alistra** [comment] 2022-07-31 09:37
I managed to do a workaround by disabling the rule. But I assume fix is planned soon? Or maybe this rule should be opt-in if it has potential to break stuff?

**Comment by calda** [comment] 2022-07-31 14:37
Agree with your assessment that this is caused by the method being `@discardableResult`. One potential fix could be to not apply this rule in cases where the property is manually annotated with a `: Void` type.

**Comment by alistra** [comment] 2022-07-31 15:18
@calda 

Probably also `Never` could be problematic?

**Comment by calda** [comment] 2022-07-31 15:19
Yeah, we have to special-case methods that return `Never`: https://github.com/nicklockwood/SwiftFormat/pull/1098

**Comment by calda** [comment] 2022-07-31 15:43
Here's a fix: https://github.com/nicklockwood/SwiftFormat/pull/1238

**Comment by nicklockwood** [comment] 2022-08-02 20:30
@alistra fix landed in 0.49.14

**Closed by nicklockwood** 2022-08-02 20:30 UTC
Labels: known issue, fixed in develop
