### ISSUE TITLE
Generic enums with type constraints fail to parse

### ISSUE THREAD

**Issue by mpsnp** [nicklockwood/SwiftFormat#276] opened 2018-07-19 13:42 UTC
If enum has generic constraints in `where`, swiftformat fails during parsing them.

Example:

```swift
enum QueryConstraint<T> where T: Equatable & Codable {
    case endAt(T)
    case equalTo(T)
    case startAt(T)
}
```

Fails with error:

```
warning: unexpected token }
```

**Comment by nicklockwood** [comment] 2018-07-23 20:43
@mpsnp fixed in 0.33.12, thanks!

**Comment by tkrajacic** [comment] 2018-10-01 15:37
This still fails to parse:

```Swift
public enum MyEnum<P, L>: Equatable, Hashable where P: Equatable & Hashable, L: Equatable & Hashable
```

So may I suggest to reopen this issue?

**Comment by nicklockwood** [comment] 2018-10-10 17:46
@tkrajacic the example you gave is working for me. It might be caused by something else in the file. Can you provide a larger code sample that I can use to reproduce the issue?

**Comment by tkrajacic** [comment] 2018-10-11 04:37
I completely stripped the file and
```Swift
public enum MyStuff<P, L>: Equatable, Hashable where P: Equatable & Hashable, L: Equatable & Hashable {
    case invalid
}
```
produces
```
running swiftformat...
warning: unexpected token } at 3:0 in /Users/tkrajacic/Developer/Projects/StairTree/frameworks/STModel/Sources/STModel/Types/PropertyValue.swift
```

**Comment by nicklockwood** [comment] 2018-10-11 08:56
@tkrajacic thanks, I can reproduce it now. The `case` appears to have been what I was missing.

**Comment by nicklockwood** [comment] 2018-10-11 13:31
@tkrajacic fixed in 0.35.7

**Closed by nicklockwood** 2018-10-11 13:31 UTC
